replicaCount: 1
image:
  repository: registry-1.docker.io/lpintofsgrp/backend-data
  tag: "{{ tag }}"
service:
  port: 8081
postgres:
  host: postgresql
  port: 5432
  database: appdb
  user: postgres
  password: "{{ postgres_password }}"