apiVersion: v1
kind: Service
metadata:
  name: backend-data
  labels:
    app: backend-data
spec:
  selector:
    app: backend-data
  ports:
    - port: {{ .Values.service.port }}        # Puerto que ven otros pods
      targetPort: {{ .Values.service.port }}  # Puerto del contenedor
